server:
  host: 0.0.0.0
  port: 8004
  use_ngrok: false
  use_auth: false
  auth_username: user
  auth_password: password
  log_file_path: logs/tts_server.log
  log_file_max_size_mb: 10
  log_file_backup_count: 5
model:
  repo_id: qwen3-tts-base
tts_engine:
  device: mps
  predefined_voices_path: voices
  reference_audio_path: reference_audio
  default_voice_id: AnthonyE.wav
paths:
  model_cache: model_cache
  output: outputs
generation_defaults:
  temperature: 0.44
  exaggeration: 1.49
  cfg_weight: 0.6
  seed: 1
  speed_factor: 1
  language: zh
audio_output:
  format: wav
  sample_rate: 22050
  max_reference_duration_sec: 30
  save_to_disk: false
ui_state:
  last_text: "\u5988 [pause:1.0s]\n\u9EBB [pause:1.0s]\n\u9A6C [pause:1.0s]\n\u9A82\
    \ [pause:1.0s]\n\u5417 [pause:1.0s]"
  last_voice_mode: clone
  last_predefined_voice: Emily.wav
  last_reference_file: ACE2.wav
  last_seed: 0
  last_chunk_size: 480
  last_split_text_enabled: true
  hide_chunk_warning: false
  hide_generation_warning: true
  theme: dark
  last_preset_name: Noir Detective Monologue
ui:
  title: Chatterbox TTS Server
  show_language_select: true
  max_predefined_voices_in_dropdown: 50
debug:
  save_intermediate_audio: false
