server:
  host: 0.0.0.0
  port: 8004
  use_ngrok: false
  use_auth: false
  auth_username: user
  auth_password: password
  log_file_path: logs/tts_server.log
  log_file_max_size_mb: 10
  log_file_backup_count: 5
model:
  repo_id: qwen3-tts-base
tts_engine:
  device: mps
  predefined_voices_path: voices
  reference_audio_path: reference_audio
  default_voice_id: AnthonyE.wav
paths:
  model_cache: model_cache
  output: outputs
generation_defaults:
  temperature: 0.3
  exaggeration: 0.9
  cfg_weight: 0.6
  seed: 0
  speed_factor: 1
  language: en
audio_output:
  format: wav
  sample_rate: 44100
  max_reference_duration_sec: 30
  save_to_disk: false
ui_state:
  last_text: "\u56DE\u5149\u8FD4\u7167"
  last_voice_mode: clone
  last_predefined_voice: Emily.wav
  last_reference_file: ACE2.wav
  last_seed: 1947
  last_chunk_size: 340
  last_split_text_enabled: true
  hide_chunk_warning: false
  hide_generation_warning: true
  theme: dark
  last_preset_name: Noir Detective Monologue
  last_qwen3_ref_text: Hello everybody, welcome, to the dabguy radio hour.  So we
    are gonna do a brief dabguy radio hour.  You guys do know how much I love to talk
    so we may continue doing it for at least one hour.  Maybe two hours.  Maybe three
    hours. We'll see how it goes.  Uhm, I hope everybody is doing well out there in
    the internet.
  last_qwen3_instruct: e-book delivery of an Alchemical/Occult topic
  last_qwen3_speaker: Chelsie
ui:
  title: Chatterbox TTS Server
  show_language_select: true
  max_predefined_voices_in_dropdown: 50
debug:
  save_intermediate_audio: false
